# See https://wiki.hyprland.org/Configuring/Monitors/
# command: hyperctl monitors all
$primary   = eDP-1
# $secondary = DP-1
$secondary = HDMI-A-1
$mainMod   = SUPER

monitor=$primary,preferred,0x0,1
# monitor=,preferred,0x-1080,1
monitor=,preferred,0x-1080,1,mirror,$primary

workspace=1,monitor:$primary
workspace=2,monitor:$primary
workspace=3,monitor:$primary
workspace=4,monitor:$primary
workspace=5,monitor:$primary
workspace=6,monitor:$primary
workspace=7,monitor:$primary
workspace=8,monitor:$primary
workspace=9,monitor:$primary
workspace=10,monitor:$primary

workspace=11,monitor:$secondary
workspace=12,monitor:$secondary
workspace=13,monitor:$secondary
workspace=14,monitor:$secondary
workspace=15,monitor:$secondary
workspace=16,monitor:$secondary
workspace=17,monitor:$secondary
workspace=18,monitor:$secondary
workspace=19,monitor:$secondary
workspace=110,monitor:$secondary

# FIXME: even if I use 2 in front it just doesn't work :c
#workspace=11,monitor:$tertiary
#workspace=12,monitor:$tertiary
#workspace=13,monitor:$tertiary
#workspace=14,monitor:$tertiary
#workspace=15,monitor:$tertiary
#workspace=16,monitor:$tertiary
#workspace=17,monitor:$tertiary
#workspace=18,monitor:$tertiary
#workspace=19,monitor:$tertiary
#workspace=110,monitor:$tertiary

# workspace=21,monitor:$tertiary
# workspace=22,monitor:$tertiary
# workspace=23,monitor:$tertiary
# workspace=24,monitor:$tertiary
# workspace=25,monitor:$tertiary
# workspace=26,monitor:$tertiary
# workspace=27,monitor:$tertiary
# workspace=28,monitor:$tertiary
# workspace=29,monitor:$tertiary
# workspace=210,monitor:$tertiary

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, exec, hyprsome workspace 1
bind = $mainMod, 2, exec, hyprsome workspace 2
bind = $mainMod, 3, exec, hyprsome workspace 3
bind = $mainMod, 4, exec, hyprsome workspace 4
bind = $mainMod, 5, exec, hyprsome workspace 5
bind = $mainMod, 6, exec, hyprsome workspace 6
bind = $mainMod, 7, exec, hyprsome workspace 7
bind = $mainMod, 8, exec, hyprsome workspace 8
bind = $mainMod, 9, exec, hyprsome workspace 9
bind = $mainMod, 0, exec, hyprsome workspace 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, exec, hyprsome movefocus 1
bind = $mainMod SHIFT, 2, exec, hyprsome movefocus 2
bind = $mainMod SHIFT, 3, exec, hyprsome movefocus 3
bind = $mainMod SHIFT, 4, exec, hyprsome movefocus 4
bind = $mainMod SHIFT, 5, exec, hyprsome movefocus 5
bind = $mainMod SHIFT, 6, exec, hyprsome movefocus 6
bind = $mainMod SHIFT, 7, exec, hyprsome movefocus 7
bind = $mainMod SHIFT, 8, exec, hyprsome movefocus 8
bind = $mainMod SHIFT, 9, exec, hyprsome movefocus 9
bind = $mainMod SHIFT, 0, exec, hyprsome movefocus 10
